version: 2.1

executors:
    go:
        docker:
            -   image: cimg/go:1.13
                environment:
                    GOFLAGS: -mod=readonly

jobs:
    test:
        executor: go

        steps:
            - checkout

            -   run:
                    name: Run tests
                    command: |
                        if [ $CIRCLE_NODE_TOTAL -gt 1 ]; then
                            export TEST_PKGS=$(echo `go list ./... | circleci tests split`)
                            export TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml
                        fi

                        make test

            -   run:
                    name: Run linter
                    command: make lint

            -   store_test_results:
                    path: build/test_results/

workflows:
    version: 2
    build:
        jobs:
            - test
